"""create approvals audit table

Revision ID: 3c11594bea19
Revises: 404e9eeb0501
Create Date: 2026-09-17 01:21:19.360610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c11594bea19'
down_revision: Union[str, Sequence[str], None] = '404e9eeb0501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('leave_request_id', sa.UUID(), nullable=False),
    sa.Column('approval_level', sa.Text(), nullable=False),
    sa.Column('approver_employee_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("approval_level IN ('manager', 'hr')", name='ck_approval_level'),
    sa.CheckConstraint("decision IN ('approved', 'rejected')", name='ck_approval_decision'),
    sa.ForeignKeyConstraint(['approver_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['leave_request_id'], ['leave_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leave_request_id', 'approval_level', name='uq_approval_per_request_level')
    )
    # ### end Alembic commands ###

    # Hand-written (autogenerate can't see triggers): reuse the DB's
    # set_updated_at() function created in migration #1.
    op.execute(
        "CREATE TRIGGER approvals_touch BEFORE UPDATE ON approvals "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS approvals_touch ON approvals;")
    op.drop_table('approvals')
    # ### end Alembic commands ###
