"""create leave_requests ledger

Revision ID: 404e9eeb0501
Revises: 8fff7931553c
Create Date: 2026-09-17 00:24:45.635341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404e9eeb0501'
down_revision: Union[str, Sequence[str], None] = '8fff7931553c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('request_no', sa.Text(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('requested_days', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('day_portion', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('medical_certificate_provided', sa.Boolean(), nullable=True),
    sa.Column('medical_certificate_reference', sa.Text(), nullable=True),
    sa.Column('employee_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending_manager', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("day_portion IS NULL OR (day_portion IN ('am', 'pm') AND start_date = end_date)", name='ck_half_day_single_date'),
    sa.CheckConstraint("leave_type IN ('annual', 'sick', 'hospitalisation')", name='ck_leave_request_type'),
    sa.CheckConstraint("status IN ('draft', 'pending_manager', 'pending_hr', 'approved', 'rejected', 'cancelled', 'escalated')", name='ck_leave_request_status'),
    sa.CheckConstraint('end_date >= start_date', name='ck_leave_dates_ordered'),
    sa.CheckConstraint('requested_days > 0', name='ck_leave_days_positive'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_no')
    )
    op.create_index('ix_leave_requests_employee_status', 'leave_requests', ['employee_id', 'status'], unique=False)
    op.create_index('uq_leave_no_active_duplicates', 'leave_requests', ['employee_id', 'leave_type', 'start_date', 'end_date'], unique=True, postgresql_where=sa.text("status NOT IN ('rejected', 'cancelled')"))
    # ### end Alembic commands ###

    # Hand-written (autogenerate can't see triggers): reuse the DB's
    # set_updated_at() function created in migration #1.
    op.execute(
        "CREATE TRIGGER leave_requests_touch BEFORE UPDATE ON leave_requests "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS leave_requests_touch ON leave_requests;")
    op.drop_index('uq_leave_no_active_duplicates', table_name='leave_requests', postgresql_where=sa.text("status NOT IN ('rejected', 'cancelled')"))
    op.drop_index('ix_leave_requests_employee_status', table_name='leave_requests')
    op.drop_table('leave_requests')
    # ### end Alembic commands ###
