"""add policy_documents and policy_chunks

Revision ID: 71b988470cbd
Revises: 8499e5334ccd
Create Date: 2026-09-14 17:13:15.568739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # fix: autogen used pgvector types but template lacked the import


# revision identifiers, used by Alembic.
revision: str = '71b988470cbd'
down_revision: Union[str, Sequence[str], None] = '8499e5334ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Hand-edit (autogenerate cannot know about it): the VECTOR column below
    # requires the pgvector extension to exist first.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('policy_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('local_path')
    )
    op.create_table('policy_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_no', sa.Text(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['policy_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_chunks')
    op.drop_table('policy_documents')
    # ### end Alembic commands ###
