"""create employees table

Revision ID: 8499e5334ccd
Revises: 
Create Date: 2026-09-14 16:17:57.589868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8499e5334ccd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('employee_no', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('employee', 'manager', 'hr', 'admin', name='employee_role', native_enum=False), server_default='employee', nullable=False),
    sa.Column('department', sa.Text(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', name='employment_type', native_enum=False), nullable=False),
    sa.Column('jurisdiction', sa.Enum('peninsular_malaysia', 'labuan', 'sabah', 'sarawak', name='jurisdiction', native_enum=False), nullable=False),
    sa.Column('employment_status', sa.Enum('active', 'resigned', 'terminated', 'inactive', name='employment_status', native_enum=False), server_default='active', nullable=False),
    sa.Column('employment_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(employment_status IN ('resigned', 'terminated')) = (employment_end_date IS NOT NULL)", name='ck_employment_status_end_date'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('employee_no')
    )
    # ### end Alembic commands ###

    # Hand-written: autogenerate knows nothing about triggers (docs/
    # FINAL_SCHEMA_V1.sql section 11). updated_at must be touched by the
    # database, because DEFAULT now() only fires on INSERT.
    op.execute(
        """
        CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER employees_touch BEFORE UPDATE ON employees
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS employees_touch ON employees;")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")
    op.drop_table('employees')
    # ### end Alembic commands ###
