"""flexible work requests + approvals extension

Revision ID: a8e02af4d7bd
Revises: 3c11594bea19
Create Date: 2026-09-17 15:34:48.339958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8e02af4d7bd'
down_revision: Union[str, Sequence[str], None] = '3c11594bea19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flexible_work_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('request_no', sa.Text(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('change_hours', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('change_days', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('change_place', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requested_arrangement', sa.Text(), nullable=False),
    sa.Column('employee_reason', sa.Text(), nullable=True),
    sa.Column('proposed_start_date', sa.Date(), nullable=True),
    sa.Column('proposed_end_date', sa.Date(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decision_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_basis_policy_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending_manager', nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'pending_manager', 'pending_hr', 'approved', 'rejected', 'withdrawn', 'escalated')", name='ck_fwa_status'),
    sa.CheckConstraint('change_hours OR change_days OR change_place', name='ck_fwa_at_least_one_dimension'),
    sa.CheckConstraint('proposed_end_date IS NULL OR proposed_start_date IS NULL OR proposed_end_date >= proposed_start_date', name='ck_fwa_dates_ordered'),
    sa.ForeignKeyConstraint(['decision_basis_policy_id'], ['policy_documents.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_no')
    )
    op.create_index('ix_fwa_employee_status', 'flexible_work_requests', ['employee_id', 'status'], unique=False)
    op.add_column('approvals', sa.Column('fwa_request_id', sa.UUID(), nullable=True))
    op.alter_column('approvals', 'leave_request_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint('uq_fwa_approval_per_level', 'approvals', ['fwa_request_id', 'approval_level'])
    op.create_foreign_key('fk_approvals_fwa_request_id', 'approvals', 'flexible_work_requests', ['fwa_request_id'], ['id'], ondelete='CASCADE')
    # Hand-written: autogenerate did NOT detect this CHECK on the existing
    # table (it diffs new tables' constraints well, existing tables' poorly).
    op.create_check_constraint(
        'ck_approval_exactly_one_target',
        'approvals',
        '(leave_request_id IS NULL) <> (fwa_request_id IS NULL)',
    )
    # Hand-written: updated_at trigger for the new table, reusing the
    # set_updated_at() function from migration #1.
    op.execute(
        "CREATE TRIGGER fwa_requests_touch BEFORE UPDATE ON flexible_work_requests "
        "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS fwa_requests_touch ON flexible_work_requests;")
    op.drop_constraint('ck_approval_exactly_one_target', 'approvals', type_='check')
    # FWA decision rows cannot exist in the downgraded schema (leave_request_id
    # becomes NOT NULL); removing them is the honest meaning of this downgrade.
    op.execute("DELETE FROM approvals WHERE fwa_request_id IS NOT NULL;")
    op.drop_constraint('fk_approvals_fwa_request_id', 'approvals', type_='foreignkey')
    op.drop_constraint('uq_fwa_approval_per_level', 'approvals', type_='unique')
    op.alter_column('approvals', 'leave_request_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('approvals', 'fwa_request_id')
    op.drop_index('ix_fwa_employee_status', table_name='flexible_work_requests')
    op.drop_table('flexible_work_requests')
    # ### end Alembic commands ###
